framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: 'default'
                retry_strategy:
                    delay: 2500
                    max_retries: 5
                    multiplier: 3
        routing:
            'App\Messenger\Message\MessageInterface': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
